version: '3.8'

services:
  web:
    build: .
    container_name: php_sveltekit
    volumes:
      - ./build:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
